echo "start"
export GOOGLE_APPLICATION_CREDENTIALS="/Users/anthonykrinsky/Documents/Dataflow/service-account-key/neo4j-se-team-201905-sa-key.json"
echo "application-credentials"
gcloud auth activate-service-account "1055617507124-compute@developer.gserviceaccount.com" --verbosity="debug" --key-file="/Users/anthonykrinsky/Documents/Dataflow/service-account-key/neo4j-se-team-201905-sa-key.json" --project="neo4j-se-team-201905"
echo "activated-service-account"
export TEMPLATE_GCS_LOCATION="gs://neo4j-dataflow/flex-templates/images/googlecloud-to-neo4j-image-spec.json"
export REGION="us-central1"
gcloud dataflow flex-template run "test-text-inline-cli-`date +%Y%m%d-%H%M%S`" --verbosity=debug --template-file-gcs-location="$TEMPLATE_GCS_LOCATION" --region "$REGION" --parameters jobSpecUri="gs://neo4j-dataflow/job-specs/testing/text/inline-northwind-jobspec.json" --parameters neo4jConnectionUri="gs://neo4j-dataflow/job-specs/testing/connection/auradb-free-connection.json"
echo "ran-dataflow-flex-templates"